[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#444444"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#a7aaad"

# Color used for almost all text.
textColor = "#f0f6fc"

[client]
toolbarMode = "minimal"